---
- name: Execute the script worker-init.sh
  script: worker-init.sh

- name: Copy the containerd configuration file
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: Execute the script worker-install.sh
  script: worker-install.sh
