---
- name: Execute the script master-init.sh
  script: master-init.sh

- name: Copy the containerd configuration file
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: Execute the script master-inst.sh
  script: master-install.sh
