apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: dev

spec:
  rules:
    - host: digitaljukeboxg6bis.reseau-labo.fr
      http:
        paths:
          - path: /keycloak
            pathType: Prefix
            backend:
              service:
                name: keycloak-0
                port:
                  number: 80
